### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Anti24s** [Pymmdrza/LiteHuntRanger#2]
![9515CCC9-09CE-48DB-8F45-394F20691870](https://github.com/Pymmdrza/LiteHuntRanger/assets/144484968/4d61ceb7-5d4e-42de-8632-fc79bd9408a1)

it keeps coming up with this error everytime i try to open it

**Comment by Pymmdrza** [comment]
> ![9515CCC9-09CE-48DB-8F45-394F20691870](https://user-images.githubusercontent.com/144484968/267107435-4d61ceb7-5d4e-42de-8632-fc79bd9408a1.png)
> 
> it keeps coming up with this error everytime i try to open it

**This problem is from the side of your system, the script works without any errors.** You may have changed the `name of the files` or you are not running the `terminal in the right place`

search on google : help about running python script
